### PR TITLE
Add custom user macros for cancel, resume and pause demon macros

### PR DESCRIPTION
**Pull request by sermayoral**
Adding post custom user macros form cancel, resume and pause :-)

### CODE REVIEW

**Comment by 3DPrintDemon** [comment]
Awesome additions I’ll look at these when I have some time this week. You know it’s funny the |lower thing I always forget about lol 😂 🙈
Too busy trying to plan out the system while writing & testing I guess 😅

**Comment by sermayoral** [comment]
Take all the time you need, of course, and feel free to modify whatever you consider in the pull request. The truth is that I love these macros, and I think that with a touch of the best of each one, and mainly with your contributions, they can become a reference.

Thank you!!

**Comment by 3DPrintDemon** [comment]
Thats very kind of you, thank you so much! I'm glad you like my work. I'll hopefully have some time this weekend if my evenings are busy.

**Comment by 3DPrintDemon** [comment]
Hi, sorry it took a little time. I was busy writing some updates to help everyone install, maintain & update their files. All items in the PR have also been included with the v2.94 release on one shape or form! I hope you like the update, there's been a big change in how the system works now. The user files are now able to be used outside the main DIR & update manager used as well as shell extensions for file management on install & on future updates.

**Pull request closed without merging**
